# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c7b51029c26ca8065ba0135d9a288e63fb8c502ce2c9809fecf5fb5cc1526b2ab2a3ab4c37a609bea0fc81c9acec4cbe0e71700057d975265c73822142ad103

test:
  secret_key_base: f0375f92a5325fa57113b4bc0a1dc5a2d0fa49bd2587c4c87cb4bc67aabc3aa38b3cc4bca872800cc14f155ea076a7914f029c9f85bb121752d593812fd0de04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
